//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Khachhangs = new HashSet<Khachhang>();
            this.Nhanviens = new HashSet<Nhanvien>();
        }
    
        public System.Guid AccountId { get; set; }
        public string AccountName { get; set; }
        public string AccountPassword { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Khachhang> Khachhangs { get; set; }
        public virtual ICollection<Nhanvien> Nhanviens { get; set; }
    }
}
