//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietPhieuxuat
    {
        public System.Guid ChitietPhieuxuatId { get; set; }
        public Nullable<System.Guid> PhieuxuatId { get; set; }
        public Nullable<System.Guid> HanghoaId { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> Step { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.Guid> ChitietDonhangId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<double> Thanhtien { get; set; }
    
        public virtual Hanghoa Hanghoa { get; set; }
        public virtual Phieuxuat Phieuxuat { get; set; }
    }
}
