//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongnoNhap
    {
        public System.Guid CongnoNhapId { get; set; }
        public Nullable<System.Guid> NhaCungcapId { get; set; }
        public Nullable<System.DateTime> NgayGiaodich { get; set; }
        public Nullable<double> SoduTruocGiaodich { get; set; }
        public Nullable<double> SotienGiaodich { get; set; }
        public string Tongno { get; set; }
        public Nullable<System.DateTime> NgayHentra { get; set; }
        public Nullable<System.Guid> NhanvienId { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> Step { get; set; }
        public byte[] Version { get; set; }
    
        public virtual NhaCungcap NhaCungcap { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
    }
}
