//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupItem
    {
        public GroupItem()
        {
            this.Items = new HashSet<Item>();
        }
    
        public System.Guid GroupItemId { get; set; }
        public string Tennhom { get; set; }
        public string Mota { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
