//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HanghoaNhaCungcap
    {
        public System.Guid HanghoaNhaCungcapId { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> HanghoaId { get; set; }
        public Nullable<System.Guid> NhaCungcapId { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> Step { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Hanghoa Hanghoa { get; set; }
        public virtual NhaCungcap NhaCungcap { get; set; }
    }
}
