//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hanghoa
    {
        public Hanghoa()
        {
            this.ChitietDonhangs = new HashSet<ChitietDonhang>();
            this.ChitietPhieunhaps = new HashSet<ChitietPhieunhap>();
            this.ChitietPhieuxuats = new HashSet<ChitietPhieuxuat>();
            this.Dongias = new HashSet<Dongia>();
            this.HanghoaNhaCungcaps = new HashSet<HanghoaNhaCungcap>();
            this.LoHanghoas = new HashSet<LoHanghoa>();
            this.ThuoctinhHanghoas = new HashSet<ThuoctinhHanghoa>();
        }
    
        public System.Guid HanghoaId { get; set; }
        public string Code { get; set; }
        public string TenHanghoa { get; set; }
        public Nullable<System.Guid> NhomHanghoaId { get; set; }
        public Nullable<double> Giagoc { get; set; }
        public string Barcode { get; set; }
        public Nullable<System.Guid> DonviId { get; set; }
        public string LinkHinhanh { get; set; }
        public string Ghichu { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Step { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> NgayCapnhat { get; set; }
        public string LinkHinhanh_Web { get; set; }
    
        public virtual ICollection<ChitietDonhang> ChitietDonhangs { get; set; }
        public virtual ICollection<ChitietPhieunhap> ChitietPhieunhaps { get; set; }
        public virtual ICollection<ChitietPhieuxuat> ChitietPhieuxuats { get; set; }
        public virtual ICollection<Dongia> Dongias { get; set; }
        public virtual Donvi Donvi { get; set; }
        public virtual NhomHanghoa NhomHanghoa { get; set; }
        public virtual ICollection<HanghoaNhaCungcap> HanghoaNhaCungcaps { get; set; }
        public virtual ICollection<LoHanghoa> LoHanghoas { get; set; }
        public virtual ICollection<ThuoctinhHanghoa> ThuoctinhHanghoas { get; set; }
    }
}
