//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khachhang
    {
        public Khachhang()
        {
            this.CongnoXuats = new HashSet<CongnoXuat>();
            this.Donhangs = new HashSet<Donhang>();
        }
    
        public System.Guid KhachhangId { get; set; }
        public string Code { get; set; }
        public string HotenKhachhang { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public Nullable<bool> Gioitinh { get; set; }
        public string Diachi { get; set; }
        public string DiachiGiaohang { get; set; }
        public Nullable<System.Guid> QuanhuyenId { get; set; }
        public Nullable<System.Guid> TinhthanhId { get; set; }
        public Nullable<System.Guid> NhomKhachhangId { get; set; }
        public string Linkanh { get; set; }
        public string Congty { get; set; }
        public string Chucvu { get; set; }
        public string Email { get; set; }
        public string DiachiCongty { get; set; }
        public string PhoneCongty { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string MasoThue { get; set; }
        public string TenTaikhoan { get; set; }
        public string SoTaikhoan { get; set; }
        public string Nganhang { get; set; }
        public Nullable<double> HanmucCongno { get; set; }
        public Nullable<int> ThoigianCongno { get; set; }
        public Nullable<int> ToahangCongno { get; set; }
        public string Ghichu { get; set; }
        public Nullable<System.DateTime> NgayCapnhat { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Step { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<CongnoXuat> CongnoXuats { get; set; }
        public virtual ICollection<Donhang> Donhangs { get; set; }
        public virtual NhomKhachhang NhomKhachhang { get; set; }
        public virtual Quanhuyen Quanhuyen { get; set; }
        public virtual Tinhthanh Tinhthanh { get; set; }
    }
}
