//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public Kho()
        {
            this.Donhangs = new HashSet<Donhang>();
            this.LoHanghoas = new HashSet<LoHanghoa>();
            this.NhanvienKhoes = new HashSet<NhanvienKho>();
            this.Phieunhaps = new HashSet<Phieunhap>();
            this.Phieuxuats = new HashSet<Phieuxuat>();
        }
    
        public System.Guid KhoId { get; set; }
        public string Code { get; set; }
        public string TenKho { get; set; }
        public string Diachi { get; set; }
        public Nullable<System.Guid> QuanhuyenId { get; set; }
        public Nullable<System.Guid> TinhthanhId { get; set; }
        public string Ghichu { get; set; }
        public Nullable<System.DateTime> NgayCapnhat { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Step { get; set; }
        public byte[] Version { get; set; }
    
        public virtual ICollection<Donhang> Donhangs { get; set; }
        public virtual Quanhuyen Quanhuyen { get; set; }
        public virtual Tinhthanh Tinhthanh { get; set; }
        public virtual ICollection<LoHanghoa> LoHanghoas { get; set; }
        public virtual ICollection<NhanvienKho> NhanvienKhoes { get; set; }
        public virtual ICollection<Phieunhap> Phieunhaps { get; set; }
        public virtual ICollection<Phieuxuat> Phieuxuats { get; set; }
    }
}
