//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khuvuc
    {
        public Khuvuc()
        {
            this.Tinhthanhs = new HashSet<Tinhthanh>();
        }
    
        public System.Guid KhuvucId { get; set; }
        public string Code { get; set; }
        public string TenKhuvuc { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> Step { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> NgayCapnhat { get; set; }
    
        public virtual ICollection<Tinhthanh> Tinhthanhs { get; set; }
    }
}
