//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoHanghoa
    {
        public System.Guid LoHanghoaId { get; set; }
        public string Code { get; set; }
        public string TenloHanghoa { get; set; }
        public Nullable<System.Guid> HanghoaId { get; set; }
        public Nullable<System.Guid> KhoId { get; set; }
        public Nullable<int> Ngay { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<System.DateTime> HSD { get; set; }
        public Nullable<int> SoduDauky { get; set; }
        public int SoluongNhap { get; set; }
        public Nullable<int> SoluongXuat { get; set; }
        public Nullable<int> SoluongHuy { get; set; }
        public Nullable<int> SoluongTon { get; set; }
        public Nullable<System.Guid> NhanvienCapnhat { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> Step { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> NgayCapnhat { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Hanghoa Hanghoa { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
    }
}
