//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungcap
    {
        public NhaCungcap()
        {
            this.CongnoNhaps = new HashSet<CongnoNhap>();
            this.HanghoaNhaCungcaps = new HashSet<HanghoaNhaCungcap>();
            this.Phieunhaps = new HashSet<Phieunhap>();
        }
    
        public System.Guid NhaCungcapId { get; set; }
        public string Code { get; set; }
        public string TenNhaCungcap { get; set; }
        public string Diachi { get; set; }
        public Nullable<System.Guid> QuanhuyenId { get; set; }
        public Nullable<System.Guid> TinhthanhId { get; set; }
        public string TenCongty { get; set; }
        public string Fax { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string TenTaikhoan { get; set; }
        public string SoTaikhoan { get; set; }
        public string Nganhang { get; set; }
        public string Ghichu { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Step { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> NgayCapnhat { get; set; }
    
        public virtual ICollection<CongnoNhap> CongnoNhaps { get; set; }
        public virtual ICollection<HanghoaNhaCungcap> HanghoaNhaCungcaps { get; set; }
        public virtual Quanhuyen Quanhuyen { get; set; }
        public virtual Tinhthanh Tinhthanh { get; set; }
        public virtual ICollection<Phieunhap> Phieunhaps { get; set; }
    }
}
