//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhanvien
    {
        public Nhanvien()
        {
            this.CongnoNhaps = new HashSet<CongnoNhap>();
            this.CongnoXuats = new HashSet<CongnoXuat>();
            this.Donhangs = new HashSet<Donhang>();
            this.Donhangs1 = new HashSet<Donhang>();
            this.LoHanghoas = new HashSet<LoHanghoa>();
            this.NhanvienKhoes = new HashSet<NhanvienKho>();
            this.Phieunhaps = new HashSet<Phieunhap>();
            this.Phieuxuats = new HashSet<Phieuxuat>();
            this.Phieuxuats1 = new HashSet<Phieuxuat>();
            this.Phieuxuats2 = new HashSet<Phieuxuat>();
            this.Thuchis = new HashSet<Thuchi>();
            this.TinhtrangDonhangs = new HashSet<TinhtrangDonhang>();
            this.TinhtrangPhieunhaps = new HashSet<TinhtrangPhieunhap>();
            this.TinhtrangPhieuxuats = new HashSet<TinhtrangPhieuxuat>();
            this.Users = new HashSet<User>();
        }
    
        public System.Guid NhanvienId { get; set; }
        public string Code { get; set; }
        public string TenNhanvien { get; set; }
        public string HoNhanvien { get; set; }
        public string HovatenNhanvien { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public Nullable<System.Guid> PhongbanId { get; set; }
        public Nullable<bool> Gioitinh { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Diachi { get; set; }
        public Nullable<System.Guid> QuanhuyenId { get; set; }
        public Nullable<System.Guid> TinhthanhId { get; set; }
        public Nullable<System.DateTime> NgayBatdau { get; set; }
        public Nullable<System.DateTime> NgayKetthuc { get; set; }
        public Nullable<System.DateTime> NgayCapnhat { get; set; }
        public string Ghichu { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Step { get; set; }
        public byte[] Version { get; set; }
        public string Linkanh { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
    
        public virtual ICollection<CongnoNhap> CongnoNhaps { get; set; }
        public virtual ICollection<CongnoXuat> CongnoXuats { get; set; }
        public virtual ICollection<Donhang> Donhangs { get; set; }
        public virtual ICollection<Donhang> Donhangs1 { get; set; }
        public virtual ICollection<LoHanghoa> LoHanghoas { get; set; }
        public virtual Phongban Phongban { get; set; }
        public virtual Quanhuyen Quanhuyen { get; set; }
        public virtual Tinhthanh Tinhthanh { get; set; }
        public virtual ICollection<NhanvienKho> NhanvienKhoes { get; set; }
        public virtual ICollection<Phieunhap> Phieunhaps { get; set; }
        public virtual ICollection<Phieuxuat> Phieuxuats { get; set; }
        public virtual ICollection<Phieuxuat> Phieuxuats1 { get; set; }
        public virtual ICollection<Phieuxuat> Phieuxuats2 { get; set; }
        public virtual ICollection<Thuchi> Thuchis { get; set; }
        public virtual ICollection<TinhtrangDonhang> TinhtrangDonhangs { get; set; }
        public virtual ICollection<TinhtrangPhieunhap> TinhtrangPhieunhaps { get; set; }
        public virtual ICollection<TinhtrangPhieuxuat> TinhtrangPhieuxuats { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
