//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleRight
    {
        public System.Guid RoleRightId { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public Nullable<System.Guid> ItemId { get; set; }
        public Nullable<System.Guid> ItemChaId { get; set; }
        public Nullable<System.Guid> AssemblyFileId { get; set; }
        public Nullable<System.Guid> ServiceItemId { get; set; }
        public Nullable<int> Enable { get; set; }
        public Nullable<System.Guid> DatabaseItemId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Role Role { get; set; }
    }
}
