//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.RoleRights = new HashSet<RoleRight>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public System.Guid RoleId { get; set; }
        public string Name { get; set; }
        public string Mota { get; set; }
        public Nullable<bool> Enable { get; set; }
    
        public virtual ICollection<RoleRight> RoleRights { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
