//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ANSIPiping_old
    {
        public string SAP_m_n { get; set; }
        public string SAP_description { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> SAP_cost { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string rating { get; set; }
        public string Type { get; set; }
        public Nullable<double> Size { get; set; }
        public Nullable<double> sch { get; set; }
        public string mtl { get; set; }
        public string F11 { get; set; }
        public string F12 { get; set; }
        public Nullable<decimal> MTL1 { get; set; }
        public Nullable<decimal> MTL2 { get; set; }
        public Nullable<double> weld_time { get; set; }
        public Nullable<double> cut_prep { get; set; }
        public Nullable<double> assemble { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<decimal> MTLsub { get; set; }
        public Nullable<double> hrsweld { get; set; }
        public Nullable<double> hrsassy { get; set; }
        public int PipingId { get; set; }
        public string conduit { get; set; }
        public string Units { get; set; }
        public string method { get; set; }
    }
}
