//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_newpart
    {
        public int id { get; set; }
        public string Material { get; set; }
        public string Plnt { get; set; }
        public string MS { get; set; }
        public string PGr { get; set; }
        public string MRPCn { get; set; }
        public string SOrg { get; set; }
        public string DChl { get; set; }
        public string MG2 { get; set; }
        public string MG5 { get; set; }
        public string ProductHierarchy { get; set; }
        public string StandardPrice { get; set; }
        public string Curr { get; set; }
        public string PlantStock { get; set; }
        public string BUn { get; set; }
        public string Consumption { get; set; }
        public string BUn2 { get; set; }
        public string MaterialNumber { get; set; }
        public string PurchasingGroup { get; set; }
        public string MRPController { get; set; }
        public string ProductHierarchy2 { get; set; }
        public string PlantSpecific_Material_Status { get; set; }
        public string ValA { get; set; }
    }
}
