//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Piping_SchemParts
    {
        public int ID { get; set; }
        public Nullable<int> Schem_id { get; set; }
        public Nullable<int> Package_QTY { get; set; }
        public string PN { get; set; }
        public Nullable<int> QTY { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public Nullable<double> size { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
