//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SAPPartsImport_Temp
    {
        public int SapPartId { get; set; }
        public string Material { get; set; }
        public string MaterialNumber { get; set; }
        public string StandardPrice { get; set; }
        public string Curr { get; set; }
        public string Per { get; set; }
        public string ProductHierarchy { get; set; }
        public string TermC { get; set; }
        public string ProductHierarchy1 { get; set; }
        public string GrossWeight { get; set; }
        public string WUn { get; set; }
        public string WUn1 { get; set; }
        public string TotalStock { get; set; }
        public string BUn { get; set; }
        public string PDT { get; set; }
        public string MS { get; set; }
        public string LastUpdatedBy { get; set; }
        public string LastUpdatedDate { get; set; }
    }
}
