//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Sub_Category
    {
        public int Sub_CategoryId { get; set; }
        public int Sales_GroupId { get; set; }
        public string Sub_CategoryName { get; set; }
        public string Description { get; set; }
    
        public virtual T_SalesGroup T_SalesGroup { get; set; }
    }
}
