//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WT_ChangeRequestTag
    {
        public T_WT_ChangeRequestTag()
        {
            this.T_WT_HLD = new HashSet<T_WT_HLD>();
            this.T_WT_IT = new HashSet<T_WT_IT>();
            this.T_WT_LLD = new HashSet<T_WT_LLD>();
        }
    
        public int CR_Tag_ID { get; set; }
        public string CR_Tag_Name { get; set; }
        public string CR_Tag_Description { get; set; }
        public Nullable<int> CR_ID { get; set; }
    
        public virtual T_WT_ChangeRequest T_WT_ChangeRequest { get; set; }
        public virtual ICollection<T_WT_HLD> T_WT_HLD { get; set; }
        public virtual ICollection<T_WT_IT> T_WT_IT { get; set; }
        public virtual ICollection<T_WT_LLD> T_WT_LLD { get; set; }
    }
}
