//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WT_User
    {
        public T_WT_User()
        {
            this.T_WT_ChangeRequest = new HashSet<T_WT_ChangeRequest>();
            this.T_WT_UserProfile = new HashSet<T_WT_UserProfile>();
        }
    
        public int User_ID { get; set; }
        public string User_NTID { get; set; }
        public string User_Name { get; set; }
        public string User_Department { get; set; }
        public string User_EmailID { get; set; }
        public string User_Phone { get; set; }
        public int Project_ID { get; set; }
        public Nullable<bool> Is_Default_Project { get; set; }
    
        public virtual ICollection<T_WT_ChangeRequest> T_WT_ChangeRequest { get; set; }
        public virtual T_WT_Project T_WT_Project { get; set; }
        public virtual ICollection<T_WT_UserProfile> T_WT_UserProfile { get; set; }
    }
}
