//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WT_UserProfile
    {
        public int Profile_ID { get; set; }
        public int User_ID { get; set; }
        public Nullable<bool> IsMainProfile { get; set; }
    
        public virtual T_WT_Profile T_WT_Profile { get; set; }
        public virtual T_WT_User T_WT_User { get; set; }
    }
}
