//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WT_Project
    {
        public T_WT_Project()
        {
            this.T_WT_ChangeRequest = new HashSet<T_WT_ChangeRequest>();
            this.T_WT_HLD = new HashSet<T_WT_HLD>();
            this.T_WT_IT = new HashSet<T_WT_IT>();
            this.T_WT_LLD = new HashSet<T_WT_LLD>();
            this.T_WT_Module = new HashSet<T_WT_Module>();
            this.T_WT_Profile = new HashSet<T_WT_Profile>();
            this.T_WT_User = new HashSet<T_WT_User>();
        }
    
        public int Project_ID { get; set; }
        public string Project_Name { get; set; }
        public string Project_Number { get; set; }
        public string Project_Description { get; set; }
    
        public virtual ICollection<T_WT_ChangeRequest> T_WT_ChangeRequest { get; set; }
        public virtual ICollection<T_WT_HLD> T_WT_HLD { get; set; }
        public virtual ICollection<T_WT_IT> T_WT_IT { get; set; }
        public virtual ICollection<T_WT_LLD> T_WT_LLD { get; set; }
        public virtual ICollection<T_WT_Module> T_WT_Module { get; set; }
        public virtual ICollection<T_WT_Profile> T_WT_Profile { get; set; }
        public virtual ICollection<T_WT_User> T_WT_User { get; set; }
    }
}
