//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WT_Profile
    {
        public T_WT_Profile()
        {
            this.T_WT_UserProfile = new HashSet<T_WT_UserProfile>();
            this.T_WT_Module = new HashSet<T_WT_Module>();
        }
    
        public int Profile_ID { get; set; }
        public string Profile_Name { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<int> Project_ID { get; set; }
    
        public virtual T_WT_Project T_WT_Project { get; set; }
        public virtual ICollection<T_WT_UserProfile> T_WT_UserProfile { get; set; }
        public virtual ICollection<T_WT_Module> T_WT_Module { get; set; }
    }
}
