//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WT_Module
    {
        public T_WT_Module()
        {
            this.T_WT_ChangeRequest = new HashSet<T_WT_ChangeRequest>();
            this.T_WT_Profile = new HashSet<T_WT_Profile>();
        }
    
        public int Module_ID { get; set; }
        public Nullable<int> Project_ID { get; set; }
        public string Module_Name { get; set; }
        public string Module_Description { get; set; }
    
        public virtual ICollection<T_WT_ChangeRequest> T_WT_ChangeRequest { get; set; }
        public virtual T_WT_Project T_WT_Project { get; set; }
        public virtual ICollection<T_WT_Profile> T_WT_Profile { get; set; }
    }
}
