//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhtrangPhieunhap
    {
        public System.Guid TinhtrangPhieunhapId { get; set; }
        public Nullable<System.Guid> PhieunhapId { get; set; }
        public Nullable<System.Guid> TinhtrangId { get; set; }
        public Nullable<System.Guid> NhanvienCapnhat { get; set; }
        public Nullable<System.DateTime> NgayCapnhat { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Nhanvien Nhanvien { get; set; }
        public virtual Phieunhap Phieunhap { get; set; }
        public virtual Tinhtrang Tinhtrang { get; set; }
    }
}
