//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tinhtrang
    {
        public Tinhtrang()
        {
            this.TinhtrangDonhangs = new HashSet<TinhtrangDonhang>();
            this.TinhtrangPhieunhaps = new HashSet<TinhtrangPhieunhap>();
            this.TinhtrangPhieuxuats = new HashSet<TinhtrangPhieuxuat>();
        }
    
        public System.Guid TinhtrangId { get; set; }
        public string Code { get; set; }
        public string TenTinhtrang { get; set; }
        public string Ghichu { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> NgayCapnhat { get; set; }
        public Nullable<int> Step { get; set; }
        public byte[] Version { get; set; }
        public Nullable<bool> CanDelete { get; set; }
    
        public virtual ICollection<TinhtrangDonhang> TinhtrangDonhangs { get; set; }
        public virtual ICollection<TinhtrangPhieunhap> TinhtrangPhieunhaps { get; set; }
        public virtual ICollection<TinhtrangPhieuxuat> TinhtrangPhieuxuats { get; set; }
    }
}
